" Appearance
set guifont=Monospace\ 14

" Change some highlights in the default colorscheme
hi Title guifg=#0000ff
hi String guifg=DarkRed

" Disable bell sounds
set noerrorbells
set vb t_vb= 

" Clipboard shared with system
set clipboard=unnamedplus
