" Appearance
set guifont=SF\ Mono\ 14
set guioptions=c


" Disable bell sounds
set noerrorbells
set vb t_vb= 

" Clipboard shared with system
set clipboard=unnamedplus

" Command to update gvim's configuration
command! GRefreshVim source $MYGVIMRC

" Initial window size
set columns=100
set lines=50
