" General Settings
set nocompatible
set encoding=utf-8 
set path+=** 
set mouse=a
set wildmenu
set wildmode=list:longest,full
set wrap 
set tags+=$HOME/.local/share/tags 
set nofoldenable
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noshiftround
set scrolloff=5 
set backspace=indent,eol,start 
set ttyfast
set laststatus=2
set showcmd 
set matchpairs+=<:> 
set number 
set hidden
set splitbelow
set splitright
set autochdir
set hlsearch 
set incsearch 
set ignorecase 
set smartcase

set spelllang=en_gb

filetype off 
filetype plugin indent on 

" Settings depending on file type
autocmd Filetype tex setlocal nofoldenable " Not folding on LaTEX files
autocmd Filetype python nnoremap <F5> :w<CR>:make<CR>
autocmd Filetype python inoremap <buffer> <F5> <esc>:w<CR>:make<CR>
autocmd Filetype python setlocal makeprg=python3\ %

" Plugins
source ~/.vim/plugins.vim 

" Custom Mappings
nnoremap <C-_> :nohlsearch<CR>
nnoremap <C-/> :nohlsearch<CR>
nnoremap <Leader>c :set cursorline! cursorcolumn!<CR>

" Autoclosing mappings
inoremap {<CR> {<CR>}<C-o>O
inoremap [<CR> [<CR>]<C-o>O
inoremap (<CR> (<CR>)<C-o>O

" Start a new change before deleting with Ctrl+u, so a normal mode "u" can still
" recover the deleted word or line.  Normally Ctrl+u while in insert mode
" would delete the text without undo history and it would be lost forever.
inoremap <c-u> <c-g>u<c-u>
inoremap <c-w> <c-g>u<c-w>

" Fix typos writing with a quick keystroke
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u
 
" Automatic abreviations
iabbrev todo # TODO(alonfnt):
