" No need to be compatible with vi.
set nocompatible

" Some encoding nicesities
set encoding=utf-8 

" Recursive search on children directories to use with find.
set path+=** 

" Allows the use of the mouse to select, copy etc.
set mouse=a

" Tab completion suggestions when using vim commands.
set wildmenu
set wildmode=list:longest,full
      
" Wraps the lines so that everything can be read without horitzontal
" scrolling. I don't know if it good to have.
" set wrap 

" Don't fold sections of the file
set nofoldenable

" Insert spaces instead of tabs when pressing tab.
" Number of spaces that a tab counts for.
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Some padding to start scrolling before touching the boundary of the file.
set scrolloff=5 

" Not sure what it does.
set backspace=indent,eol,start 

" Faster terminal redraw.
set ttyfast

" Include filename in the bottom bar.
set laststatus=2

" Shows the command in the command bar even when run as a shortcut.
set showcmd 

" Not sure what it does.
set matchpairs+=<:> 

" Show row number.
set number 

" Split below when opening a new split file.
"set splitbelow

" Split on the right when opening a new file.
"set splitright

" Automatically change the root path to be in the folder where the file is.
" Let's try to start vim session from the root folder of the project so that
" we can use find.
"set autochdir

" Search settings to highligh search
"set hlsearch 
set incsearch 

" Search regardless of capital letters
set ignorecase 
set smartcase

" Set spelling language to be British english.
set spelllang=en_gb

" Include the file explorer in vim.
filetype plugin indent on 

" Disable annoying banner in file explorer
let g:netrw_banner=0

" Settings depending on file type
autocmd Filetype python setlocal makeprg=python3\ %

" Autoclosing mappings
inoremap {<CR> {<CR>}<C-o>O
inoremap [<CR> [<CR>]<C-o>O
inoremap (<CR> (<CR>)<C-o>O

" Start a new change before deleting with Ctrl+u, so a normal mode "u" can still
" recover the deleted word or line.  Normally Ctrl+u while in insert mode
" would delete the text without undo history and it would be lost forever.
inoremap <c-u> <c-g>u<c-u>
inoremap <c-w> <c-g>u<c-w>

" Fix typos writing with a quick keystroke Ctrl+l
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u
 
" Automatic abreviations
iabbrev todo # TODO(albert):

" Command to create a tags file in the root folder of a project
command! MakeTags !ctags -R --exclude=.git --exclude=.venv  .

" Command to update vim's configuration
command! RefreshVim source $MYVIMRC

" Plugins
source ~/.vim/plugins.vim 
