" My custom vimrc file.
"
" Maintainer:    Albert Alonso <aalonso@proton.me>
" Last Change:   2022 Apr 09
"
" This is the file config file that loads opeining vim.
" Some configurations are left to $VIMRUNTIME/defaults.vim to handle.
" To skip vim defaults file, uncomment the following line:
"let skip_defaults_vim


" Some encoding nicesities
set encoding=utf-8 

" Recursive search on children directories to use with find.
set path+=** 

" Allows the use of the mouse to select, copy etc.
set mouse=a

" Wraps the lines so that everything can be read without horitzontal scrolling. 
set wrap 

" Don't fold sections of the file
set nofoldenable

" Add completion wildmenu on the command line
set nowildmenu
set wildmode=list:full

" Insert spaces instead of tabs when pressing tab.
" Number of spaces that a tab counts for.
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab

" Some padding to start scrolling before touching the boundary of the file.
set scrolloff=5 

" Faster terminal redraw.
set ttyfast

" Include filename in the bottom bar.
set laststatus=2

" Not sure what it does.
set matchpairs+=<:> 

" Show row number.
set number 

" Search regardless of capital letters
set ignorecase 
set smartcase

" Set spelling language to be British english.
set spelllang=en_gb

" Include the file explorer in vim.
filetype plugin indent on 

" Disable annoying banner in file explorer
let g:netrw_banner=0

" Settings depending on file type
" For Python files -> set :make command to run current file.
autocmd Filetype python setlocal makeprg=python3\ %

" Start a new change before deleting with Ctrl+u, so a normal mode "u" can still
" recover the deleted word or line.  Normally Ctrl+u while in insert mode
" would delete the text without undo history and it would be lost forever.
inoremap <c-u> <c-g>u<c-u>
inoremap <c-w> <c-g>u<c-w>

" Fix typos writing with a quick keystroke Ctrl+l
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u

" Remove highlighting of searched words.
nnoremap <C-S> :nohlsearch<CR>
 
" Persistent undo history
set undofile
set undodir=$HOME/.cache
set undolevels=1000
set undoreload=1000

" Add a breakpoint after the current line
noremap <leader>b obreakpoint()<esc>

" Command to update vim's configuration
command! RefreshVim source $MYVIMRC

" Load Plugins
source $HOME/.vim/plugins.vim
